#!/usr/bin/env python3
"""Load FreeLLMAPI + optional Gemini keys from career-ops and configure Reticle + local .env."""

from __future__ import annotations

import json
import sqlite3
import time
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAREER_OPS = Path.home() / "career-ops"
FREELLMAPI_DB = Path.home() / "dev" / "freellmapi" / "server" / "data" / "freeapi.db"
RETICLE_DB = Path.home() / "Library/Application Support/Reticle/reticle.db"
ENV_FILE = ROOT / ".env"


def now_ms() -> int:
    return int(time.time() * 1000)


def load_freellmapi_key() -> str:
    config_path = CAREER_OPS / "extension" / "config.json"
    if config_path.is_file():
        data = json.loads(config_path.read_text())
        key = data.get("apiKey", "").strip()
        if key.startswith("freellmapi-"):
            return key

    if FREELLMAPI_DB.is_file():
        conn = sqlite3.connect(FREELLMAPI_DB)
        try:
            row = conn.execute(
                "SELECT value FROM settings WHERE key = 'unified_api_key'"
            ).fetchone()
            if row and str(row[0]).startswith("freellmapi-"):
                return str(row[0])
        finally:
            conn.close()

    raise SystemExit(
        "Could not find FreeLLMAPI key. Expected career-ops/extension/config.json "
        "or freellmapi DB at ~/dev/freellmapi."
    )


def load_env_key(path: Path, name: str) -> str | None:
    if not path.is_file():
        return None
    prefix = f"{name}="
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or not line.startswith(prefix):
            continue
        value = line[len(prefix) :].strip().strip('"').strip("'")
        return value or None
    return None


def upsert_reticle_api_key(provider: str, key: str) -> None:
    if not RETICLE_DB.parent.exists():
        RETICLE_DB.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(RETICLE_DB)
    try:
        row = conn.execute(
            "SELECT id FROM api_keys WHERE provider = ?", (provider,)
        ).fetchone()
        ts = now_ms()
        if row:
            conn.execute(
                "UPDATE api_keys SET key = ?, updated_at = ? WHERE provider = ?",
                (key, ts, provider),
            )
        else:
            conn.execute(
                "INSERT INTO api_keys (id, provider, key, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
                (uuid.uuid4().hex[:26], provider, key, ts, ts),
            )
        conn.commit()
    finally:
        conn.close()


def write_project_env(freellm_key: str, gemini_key: str | None) -> None:
    lines = [
        "# Auto-generated by scripts/setup-reticle-keys.py — do not commit",
        "MODEL_BASE_URL=http://localhost:3001/v1",
        f"MODEL_API_KEY={freellm_key}",
        "MODEL_NAME=auto",
        "ENABLE_LIVE_LLM=true",
        "API_BASE_URL=http://localhost:8001",
        "NEXT_PUBLIC_API_BASE_URL=http://localhost:8001",
        "DATABASE_URL=sqlite:///./agentops-studio.db",
        "REDIS_URL=redis://localhost:6379/0",
        "WORKER_QUEUE_NAME=agentops",
    ]
    if gemini_key:
        lines.append(f"GEMINI_API_KEY={gemini_key}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


def main() -> int:
    freellm_key = load_freellmapi_key()
    gemini_key = load_env_key(CAREER_OPS / ".env", "GEMINI_API_KEY")

    upsert_reticle_api_key("openai", freellm_key)
    print("Reticle: stored FreeLLMAPI unified key under OpenAI provider slot.")

    if gemini_key:
        upsert_reticle_api_key("google", gemini_key)
        print("Reticle: stored Gemini key under Google provider slot (works in Reticle v0.2.4).")
    else:
        print("Reticle: no GEMINI_API_KEY in career-ops/.env — skipped Google provider.")

    write_project_env(freellm_key, gemini_key)
    print(f"Wrote local secrets to {ENV_FILE} (gitignored).")
    print("Start FreeLLMAPI: cd ~/dev/freellmapi && npm run dev -w server")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
